// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9DLDnP7p5CMz2xi78-utpBnsNwUEKWKU',
    appId: '1:129449023297:web:9419c84b4ca0fc9404f3c0',
    messagingSenderId: '129449023297',
    projectId: 'simple-social-app-1ca0c',
    authDomain: 'simple-social-app-1ca0c.firebaseapp.com',
    storageBucket: 'simple-social-app-1ca0c.appspot.com',
    measurementId: 'G-CMTLEPMD9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByaEWifM9ZGk8vOFlgqnu1re2nxeHvqZg',
    appId: '1:129449023297:android:9071cf6ce77d4c9a04f3c0',
    messagingSenderId: '129449023297',
    projectId: 'simple-social-app-1ca0c',
    storageBucket: 'simple-social-app-1ca0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvmpQT3W2ATKlVERnrpvMh7UGB86B5DNQ',
    appId: '1:129449023297:ios:d2e5abc95edb81d004f3c0',
    messagingSenderId: '129449023297',
    projectId: 'simple-social-app-1ca0c',
    storageBucket: 'simple-social-app-1ca0c.appspot.com',
    iosBundleId: 'com.example.sMediaApp',
  );
}
